name: ICS Generator Runner

on:
  push:
    branches: [master]

jobs:
  generate-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          persist-credentials: false
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: python icsgen.py
