name: ICS Generator Runner

on:
  push:
    branches: [master]
    paths-ignore:
      - 'ics/**'

jobs:
  generate-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.COMMIT_TOKEN }}
          persist-credentials: true
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: python icsgen.py
      - name: Commit ICS Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Generated ICS files'
          commit_user_name: 'ICS-Generator [GH]'
          commit_email: 'github-actions@noreply.github.com'
          commit_author: 'ICS-Generator [GH] <github-actions@noreply.github.com>'
